//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GDDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_GDDEMO_DIALOG               102
#define IDR_MAINFRAME                   128
#define IDD_DLGCOM                      129
#define IDD_DLGPWD                      131
#define IDD_DLGUSER                     132
#define IDD_DIALOG_Note                 138
#define IDD_DLG_Note                    138
#define IDD_DIALOG_RNote                139
#define IDD_DLG_RNote                   139
#define IDD_DIALOG_IMGDEMO              140
#define IDB_BITMAP_PREVIEW              141
#define IDD_DLG_FingerDB                145
#define IDR_ACCELERATOR1                148
#define IDD_USERDEFINE                  151
#define IDI_HEADICON                    154
#define IDC_BUTTON1                     1000
#define IDC_BUTTON2                     1001
#define IDC_BUTTON3                     1002
#define IDC_BUTTON4                     1003
#define IDC_BUTTON5                     1004
#define IDC_BUTTON7                     1006
#define IDC_BUTTON8                     1007
#define IDC_BUTTON9                     1008
#define IDC_BUTTON10                    1009
#define IDC_LISTUSER                    1010
#define IDC_EDIT1                       1011
#define IDC_BTN_RANDOM                  1011
#define IDC_INFO                        1012
#define IDC_IMAGE                       1013
#define IDC_COMBO1                      1014
#define IDC_BTN_IMGDEMO                 1014
#define IDC_COMBO2                      1015
#define IDC_BUTTON6                     1016
#define IDC_EDIT2                       1017
#define IDC_BUTTON11                    1018
#define IDC_BTN_SAVEBMP                 1018
#define IDC_TIP                         1019
#define IDC_BTN_DLBMP                   1020
#define IDC_BTN_WNOTE                   1021
#define IDC_BTN_RNOTE                   1022
#define IDC_ADDR                        1023
#define IDC_BTN_RNUM                    1023
#define IDC_COMBO3                      1024
#define IDC_BTN_BIN                     1024
#define IDC_BTN_THIN                    1025
#define IDC_CHKDEV                      1026
#define IDC_USERNAME                    1027
#define IDC_BTN_TZ                      1027
#define IDC_COMBO_BAUD                  1028
#define IDC_COMBO_PAKAGESIZE            1029
#define IDC_COMBO_LEVEL                 1030
#define IDC_Note                        1030
#define IDC_EDIT_PAGE                   1031
#define IDC_BTN_ORIBMP                  1031
#define IDC_BUTTON_BIN                  1034
#define IDC_BUTTON_THIN                 1035
#define IDC_BUTTON_TZ                   1036
#define IDC_IMAGE_PRE                   1037
#define IDC_EDIT_RUN_NUM                1038
#define IDC_BTN_RUN                     1039
#define IDC_BTN_GETPATH                 1040
#define IDC_EDIT_PATH                   1041
#define IDC_EDIT_SIG_NUM                1042
#define IDC_BTN_SIG                     1043
#define IDC_BTN_CANCEL_RUN              1044
#define IDC_EDIT_NUMPFIN                1045
#define IDC_BTN_GETDB                   1046
#define IDC_BTN_CANCEL_SIG              1046
#define IDC_Preview                     1047
#define IDC_BUTTON12                    1048
#define IDC_Exit                        1048
#define IDC_BUTTON13                    1049
#define IDC_Path                        1050
#define IDC_BUTTON14                    1051
#define IDC_GetImgCon                   1051
#define IDC_OpenDev                     1052
#define IDC_BUTTON15                    1054
#define IDC_USERDEFINE                  1054
#define IDC_DBINFO                      1055
#define IDC_FINGERNUM                   1056
#define IDC_FINGERPATH                  1057
#define IDC_GETIMAGCON                  1058
#define IDC_IMAGENUM1                   1059
#define IDC_GETONE                      1060
#define IDC_IMAGENUM2                   1061
#define IDC_PAGE                        1062
#define IDC_SETTING                     1063
#define IDC_COM                         1064
#define IDC_IMGPREVIEW                  1065
#define IDC_HDINFO                      1066
#define IDC_INIT                        1067
#define IDC_DEVSETTING                  1068
#define IDC_BANDRATE                    1069
#define IDC_PACKAGESIZE                 1070
#define IDC_SECURELEVEL                 1071
#define IDC_DB                          1072
#define IDC_IMAGEMANAGE                 1073
#define IDC_FINGERENROLL                1074
#define IDC_SEARCH                      1075
#define IDC_SPECULE                     1076
#define IDC_DOWITHIMG                   1077
#define IDC_COMLANG                     1082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        156
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
